### ISSUE TITLE
API change proposal

### ISSUE THREAD

**Issue by peaonunes** [titel-media/react-apollo-multiple-clients#1]
Hello, first of all great work on it! You took the ideia to another level with this generic solution! I have a simple change proposal in the package.

I was wondering, since `withMultipleClients` is a`HOC` which returns the component wrapped in one of the clients (the client chose by the namespace) should not it be called `withClient`?

**Comment by dazlious** [comment]
Hey @peaonunes, thx for the input. Very much appreciated. Did exactly that.

https://www.npmjs.com/package/@titelmedia/react-apollo-multiple-clients/v/2.0.0

https://github.com/titel-media/react-apollo-multiple-clients/commit/a17e13a704bfaf4b8e9b65ab3c3d9fcff199c6b6
