### ISSUE TITLE
Default client for provider

### ISSUE THREAD

**Issue by peaonunes** [titel-media/react-apollo-multiple-clients#3]
Come to me that it might be useful to have a `default` field in `clients` object and when it is declared the `ApolloMultipleClientsProvider `. If this field is set the code could provide the `default` client through `context` as `ApolloProvider` does and would not be necessary to use `withClient` in this case. It can make the code more cleaner and only use the `withClient` when it is really necessary to chose from one of the clients.

That can be a huge change in `ApolloMultipleClientsProvider` so I do not know yet if the gains justify the cost of doing it, but I thought about it and decided to suggest anyway. If I get a spare time this week I will try this approach.

**Comment by dazlious** [comment]
I guess you did not get spare time ;)

We have a with client around our whole application. Therefore, no need to use withClient, but when you want to override it inside a different component.

Maybe I got you wrong, but I would say that this default-approach is already done by concept.

**Comment by peaonunes** [comment]
You totally right, I have misunderstand this.
Great work anyway!
